org.gradle.jvmargs=-Xmx1G
org.gradle.configuration-cache=true

fabric_loader_version=0.18.2
fabric_api_version=0.139.4+1.21.11

## Environment Properties

minecraft_version=1.21.11
minecraft_version_range=[1.21.11,)
neo_version=21.11.3-beta
neo_version_range=[21.11,)
loader_version_range=[4,)

parchment_minecraft_version=1.21.10
parchment_mappings_version=2025.10.12

## Mod Properties

mod_id=valhelsia_core
mod_name=Valhelsia Core
mod_license=All Rights Reserved
mod_version=1.1.5
mod_group_id=net.valhelsia
mod_authors=Khytwel, stal111, Vaelzan
mod_description=
